# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20160731_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2016, 8, 3)),
            preserve_default=False,
        ),
    ]
