# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20160805_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
