# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20160806_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSociety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('remarks', models.CharField(blank=True, max_length=150)),
                ('society', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_booking', to='rooms.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_booking', to='rooms.UserProfile')),
            ],
        ),
    ]
