# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20160819_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='id',
        ),
        migrations.AddField(
            model_name='society',
            name='society_id',
            field=models.CharField(default='aaaa', max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
