# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_verifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShibLoginToken',
            fields=[
                ('sid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shib_login_token', to='rooms.UserProfile')),
            ],
        ),
    ]
