# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_shiblogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='No Department', max_length=100),
        ),
    ]
