# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('user_id', models.IntegerField(default=180, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
