# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.TimeField(),
        ),
    ]
